// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCwYlwn3wySwl-SgoHrclkUCgIB8ZrbMQ',
    appId: '1:755422449419:web:f39268331a7b2213b25c0e',
    messagingSenderId: '755422449419',
    projectId: 'campusswap-8f935',
    authDomain: 'campusswap-8f935.firebaseapp.com',
    storageBucket: 'campusswap-8f935.appspot.com',
    measurementId: 'G-9EQ5FXZQ34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjDoEnsgMUnA6k2S829xEQxR_v-VW6TWM',
    appId: '1:755422449419:android:44d69f4930dac1dfb25c0e',
    messagingSenderId: '755422449419',
    projectId: 'campusswap-8f935',
    storageBucket: 'campusswap-8f935.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSQ4MhJZzz4oTsxaYc6mePoR7X6Z9_kyE',
    appId: '1:755422449419:ios:339730ea738e1815b25c0e',
    messagingSenderId: '755422449419',
    projectId: 'campusswap-8f935',
    storageBucket: 'campusswap-8f935.appspot.com',
    iosBundleId: 'com.impossibleshadowstorm.campusSwap',
  );
}
